import type { Category, Subcategory, Video } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Moda', slug: 'moda', order: 1, created_at: new Date().toISOString() },
  { id: '2', name: 'Fashion Shows', slug: 'fashion-shows', order: 2, created_at: new Date().toISOString() },
  { id: '3', name: 'Backstage', slug: 'backstage', order: 3, created_at: new Date().toISOString() },
];

export const subcategories: Subcategory[] = [
  { id: 'alta-moda', name: 'Alta Moda', slug: 'alta-moda', category_id: '1', order: 1, created_at: new Date().toISOString() },
  { id: 'pret-a-porter', name: 'Prêt-à-Porter', slug: 'pret-a-porter', category_id: '1', order: 2, created_at: new Date().toISOString() },
  { id: 'fashion-week', name: 'Fashion Week', slug: 'fashion-week', category_id: '2', order: 1, created_at: new Date().toISOString() },
  { id: 'dietro-le-quinte', name: 'Dietro le Quinte', slug: 'dietro-le-quinte', category_id: '3', order: 1, created_at: new Date().toISOString() },
];

export const videos: Video[] = [
  {
    id: '1',
    title: 'Milano Fashion Week 2025',
    description: 'Le migliori collezioni della Milano Fashion Week primavera/estate 2025',
    video_url: 'https://example.com/video1.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/9511237/pexels-photo-9511237.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 1800,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: true,
    created_at: new Date().toISOString(),
    views: 45000,
  },
  {
    id: '2',
    title: 'Alta Moda Italiana',
    description: 'Un viaggio nell\'eccellenza della moda italiana',
    video_url: 'https://example.com/video2.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/17244455/pexels-photo-17244455.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 1200,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: true,
    created_at: new Date().toISOString(),
    views: 42000,
  },
  {
    id: '3',
    title: 'Street Style Milano',
    description: 'I look più interessanti dalle strade di Milano',
    video_url: 'https://example.com/video3.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/13929224/pexels-photo-13929224.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 900,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: true,
    created_at: new Date().toISOString(),
    views: 38000,
  },
  {
    id: '4',
    title: 'Backstage Gucci',
    description: 'Dietro le quinte della sfilata Gucci',
    video_url: 'https://example.com/video4.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1321943/pexels-photo-1321943.jpeg',
    duration: 600,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 25000,
  },
  {
    id: '5',
    title: 'Paris Fashion Week',
    description: 'Le tendenze dalla capitale della moda',
    video_url: 'https://example.com/video5.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/5185594/pexels-photo-5185594.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 2100,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: true,
    created_at: new Date().toISOString(),
    views: 50000,
  },
  {
    id: '6',
    title: 'Haute Couture',
    description: 'L\'arte dell\'alta moda francese',
    video_url: 'https://example.com/video6.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg',
    duration: 1500,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '7',
    title: 'Street Fashion Tokyo',
    description: 'Lo street style unico di Tokyo',
    video_url: 'https://example.com/video7.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg',
    duration: 1050,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '8',
    title: 'Backstage Prada',
    description: 'Il backstage esclusivo della sfilata Prada',
    video_url: 'https://example.com/video8.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1488501/pexels-photo-1488501.jpeg',
    duration: 720,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '9',
    title: 'Alta Moda Parigi',
    description: 'Le creazioni più esclusive dalla settimana della moda parigina',
    video_url: 'https://example.com/video9.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/19250302/pexels-photo-19250302.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 1350,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: true,
    created_at: new Date().toISOString(),
    views: 35000,
  },
  {
    id: '10',
    title: 'Alta Moda Roma',
    description: 'L\'eleganza classica della moda romana',
    video_url: 'https://example.com/video10.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1381556/pexels-photo-1381556.jpeg',
    duration: 1280,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '11',
    title: 'Alta Moda New York',
    description: 'Lo stile inconfondibile della Grande Mela',
    video_url: 'https://example.com/video11.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1631181/pexels-photo-1631181.jpeg',
    duration: 1420,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '12',
    title: 'Alta Moda Londra',
    description: 'L\'innovazione della moda britannica',
    video_url: 'https://example.com/video12.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
    duration: 1180,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '13',
    title: 'Alta Moda Tokyo',
    description: 'La fusione tra tradizione e modernità giapponese',
    video_url: 'https://example.com/video13.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg',
    duration: 1520,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '14',
    title: 'Alta Moda Seoul',
    description: 'Il minimalismo elegante della moda coreana',
    video_url: 'https://example.com/video14.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg',
    duration: 1380,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '15',
    title: 'Alta Moda Firenze',
    description: 'L\'artigianalità toscana nell\'alta moda',
    video_url: 'https://example.com/video15.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
    duration: 1240,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '16',
    title: 'Alta Moda Berlin',
    description: 'Lo stile avant-garde della moda tedesca',
    video_url: 'https://example.com/video16.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1321943/pexels-photo-1321943.jpeg',
    duration: 1310,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '17',
    title: 'Alta Moda Copenhagen',
    description: 'Il design scandinavo nell\'alta moda',
    video_url: 'https://example.com/video17.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg',
    duration: 1290,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '18',
    title: 'Alta Moda Barcelona',
    description: 'La creatività spagnola nell\'alta moda',
    video_url: 'https://example.com/video18.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg',
    duration: 1360,
    year: 2025,
    subcategory_id: 'alta-moda',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '19',
    title: 'Street Style Parigi',
    description: 'Gli outfit più trendy dalle vie parigine',
    video_url: 'https://example.com/video19.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/9502500/pexels-photo-9502500.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 840,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: true,
    created_at: new Date().toISOString(),
    views: 35000,
  },
  {
    id: '20',
    title: 'Street Style New York',
    description: 'Lo street style cosmopolita di New York',
    video_url: 'https://example.com/video20.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg',
    duration: 920,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '21',
    title: 'Street Style Londra',
    description: 'L\'eclettismo della moda di strada londinese',
    video_url: 'https://example.com/video21.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1381556/pexels-photo-1381556.jpeg',
    duration: 880,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '22',
    title: 'Street Style Seoul',
    description: 'Le tendenze K-fashion dalle strade di Seoul',
    video_url: 'https://example.com/video22.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1631181/pexels-photo-1631181.jpeg',
    duration: 960,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '23',
    title: 'Street Style Berlin',
    description: 'Lo stile underground della capitale tedesca',
    video_url: 'https://example.com/video23.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
    duration: 810,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '24',
    title: 'Street Style Los Angeles',
    description: 'Il casual chic della West Coast',
    video_url: 'https://example.com/video24.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg',
    duration: 870,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '25',
    title: 'Street Style Copenhagen',
    description: 'Il minimalismo nordico nello street style',
    video_url: 'https://example.com/video25.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg',
    duration: 790,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '26',
    title: 'Street Style Shanghai',
    description: 'L\'innovazione della moda di strada cinese',
    video_url: 'https://example.com/video26.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
    duration: 930,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '27',
    title: 'Street Style Amsterdam',
    description: 'Lo stile rilassato e cool di Amsterdam',
    video_url: 'https://example.com/video27.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1321943/pexels-photo-1321943.jpeg',
    duration: 850,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '28',
    title: 'Street Style Stockholm',
    description: 'Il design funzionale dello street style svedese',
    video_url: 'https://example.com/video28.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg',
    duration: 820,
    year: 2025,
    subcategory_id: 'pret-a-porter',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '29',
    title: 'Sfilata Versace 2025',
    description: 'La collezione primavera/estate Versace',
    video_url: 'https://example.com/video29.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/8793626/pexels-photo-8793626.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 1890,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: true,
    created_at: new Date().toISOString(),
    views: 35000,
  },
  {
    id: '30',
    title: 'Sfilata Armani 2025',
    description: 'L\'eleganza senza tempo di Giorgio Armani',
    video_url: 'https://example.com/video30.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1488501/pexels-photo-1488501.jpeg',
    duration: 2050,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '31',
    title: 'Sfilata Dolce & Gabbana 2025',
    description: 'Il lusso mediterraneo di D&G',
    video_url: 'https://example.com/video31.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg',
    duration: 1950,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '32',
    title: 'Sfilata Valentino 2025',
    description: 'La nuova era romantica di Valentino',
    video_url: 'https://example.com/video32.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1381556/pexels-photo-1381556.jpeg',
    duration: 1820,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '33',
    title: 'Sfilata Fendi 2025',
    description: 'L\'innovazione nella tradizione Fendi',
    video_url: 'https://example.com/video33.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1631181/pexels-photo-1631181.jpeg',
    duration: 1780,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '34',
    title: 'Sfilata Bottega Veneta 2025',
    description: 'Il lusso discreto di Bottega Veneta',
    video_url: 'https://example.com/video34.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
    duration: 1710,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '35',
    title: 'Sfilata Etro 2025',
    description: 'I pattern iconici di Etro per il 2025',
    video_url: 'https://example.com/video35.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg',
    duration: 1650,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '36',
    title: 'Sfilata Max Mara 2025',
    description: 'La sofisticatezza contemporanea di Max Mara',
    video_url: 'https://example.com/video36.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg',
    duration: 1840,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '37',
    title: 'Sfilata Tod\'s 2025',
    description: 'L\'eleganza casual di Tod\'s',
    video_url: 'https://example.com/video37.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
    duration: 1620,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '38',
    title: 'Sfilata Missoni 2025',
    description: 'I colori vibranti della collezione Missoni',
    video_url: 'https://example.com/video38.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1321943/pexels-photo-1321943.jpeg',
    duration: 1730,
    year: 2025,
    subcategory_id: 'fashion-week',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '39',
    title: 'Backstage Chanel',
    description: 'I preparativi dietro le quinte di Chanel',
    video_url: 'https://example.com/video39.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/7446911/pexels-photo-7446911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080',
    duration: 680,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: true,
    created_at: new Date().toISOString(),
    views: 35000,
  },
  {
    id: '40',
    title: 'Backstage Dior',
    description: 'Il dietro le quinte della maison Dior',
    video_url: 'https://example.com/video40.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg',
    duration: 750,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '41',
    title: 'Backstage Louis Vuitton',
    description: 'L\'energia del backstage Louis Vuitton',
    video_url: 'https://example.com/video41.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1488501/pexels-photo-1488501.jpeg',
    duration: 690,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '42',
    title: 'Backstage Hermès',
    description: 'La precisione artigianale nel backstage Hermès',
    video_url: 'https://example.com/video42.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg',
    duration: 710,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '43',
    title: 'Backstage Balenciaga',
    description: 'L\'innovazione radicale dietro le quinte',
    video_url: 'https://example.com/video43.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1381556/pexels-photo-1381556.jpeg',
    duration: 640,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '44',
    title: 'Backstage Saint Laurent',
    description: 'Il rock chic nel backstage Saint Laurent',
    video_url: 'https://example.com/video44.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1631181/pexels-photo-1631181.jpeg',
    duration: 730,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '45',
    title: 'Backstage Givenchy',
    description: 'L\'eleganza parigina dietro le quinte Givenchy',
    video_url: 'https://example.com/video45.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
    duration: 670,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '46',
    title: 'Backstage Balmain',
    description: 'Il glamour nel backstage Balmain',
    video_url: 'https://example.com/video46.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg',
    duration: 700,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '47',
    title: 'Backstage Celine',
    description: 'Il minimalismo chic dietro le quinte Celine',
    video_url: 'https://example.com/video47.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg',
    duration: 660,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
  {
    id: '48',
    title: 'Backstage Burberry',
    description: 'La tradizione britannica nel backstage Burberry',
    video_url: 'https://example.com/video48.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
    duration: 740,
    year: 2025,
    subcategory_id: 'dietro-le-quinte',
    featured: false,
    created_at: new Date().toISOString(),
    views: 20000,
  },
];
