import type { Category, Subcategory, Video } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Moda', slug: 'moda', order: 1, created_at: new Date().toISOString() },
  { id: '2', name: 'Fashion Shows', slug: 'fashion-shows', order: 2, created_at: new Date().toISOString() },
  { id: '3', name: 'Backstage', slug: 'backstage', order: 3, created_at: new Date().toISOString() },
];

export const subcategories: Subcategory[] = [
  { id: '1', name: 'Alta Moda', slug: 'alta-moda', category_id: '1', order: 1, created_at: new Date().toISOString() },
  { id: '2', name: 'Street Style', slug: 'street-style', category_id: '1', order: 2, created_at: new Date().toISOString() },
  { id: '3', name: 'Sfilate 2025', slug: 'sfilate-2025', category_id: '2', order: 1, created_at: new Date().toISOString() },
  { id: '4', name: 'Backstage Esclusivi', slug: 'backstage-esclusivi', category_id: '3', order: 1, created_at: new Date().toISOString() },
];

export const videos: Video[] = [
  {
    id: '1',
    title: 'Milano Fashion Week 2025',
    description: 'Le migliori collezioni della Milano Fashion Week primavera/estate 2025',
    video_url: 'https://example.com/video1.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
    duration: 1800,
    year: 2025,
    subcategory_id: '3',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Alta Moda Italiana',
    description: 'Un viaggio nell\'eccellenza della moda italiana',
    video_url: 'https://example.com/video2.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
    duration: 1200,
    year: 2025,
    subcategory_id: '1',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Street Style Milano',
    description: 'I look più interessanti dalle strade di Milano',
    video_url: 'https://example.com/video3.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg',
    duration: 900,
    year: 2025,
    subcategory_id: '2',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Backstage Gucci',
    description: 'Dietro le quinte della sfilata Gucci',
    video_url: 'https://example.com/video4.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1321943/pexels-photo-1321943.jpeg',
    duration: 600,
    year: 2025,
    subcategory_id: '4',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Paris Fashion Week',
    description: 'Le tendenze dalla capitale della moda',
    video_url: 'https://example.com/video5.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg',
    duration: 2100,
    year: 2025,
    subcategory_id: '3',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Haute Couture',
    description: 'L\'arte dell\'alta moda francese',
    video_url: 'https://example.com/video6.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg',
    duration: 1500,
    year: 2025,
    subcategory_id: '1',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Street Fashion Tokyo',
    description: 'Lo street style unico di Tokyo',
    video_url: 'https://example.com/video7.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg',
    duration: 1050,
    year: 2025,
    subcategory_id: '2',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Backstage Prada',
    description: 'Il backstage esclusivo della sfilata Prada',
    video_url: 'https://example.com/video8.mp4',
    thumbnail_url: 'https://images.pexels.com/photos/1488501/pexels-photo-1488501.jpeg',
    duration: 720,
    year: 2025,
    subcategory_id: '4',
    featured: false,
    created_at: new Date().toISOString(),
  },
];
