/*
  # Create Designers Table

  1. New Tables
    - `designers`
      - `id` (uuid, primary key)
      - `name` (text, unique)
      - `slug` (text, unique)
      - `created_at` (timestamp)
  
  2. Security
    - Enable RLS on `designers` table
    - Add policy for public read access
    - Add policy for authenticated insert/update/delete
*/

CREATE TABLE IF NOT EXISTS designers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE designers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view designers"
  ON designers
  FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert designers"
  ON designers
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update designers"
  ON designers
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete designers"
  ON designers
  FOR DELETE
  TO authenticated
  USING (true);

-- Insert all designers
INSERT INTO designers (name, slug) VALUES
  ('Coco Chanel', 'coco-chanel'),
  ('Karl Lagerfeld', 'karl-lagerfeld'),
  ('Christian Dior', 'christian-dior'),
  ('Yves Saint Laurent', 'yves-saint-laurent'),
  ('Hubert de Givenchy', 'hubert-de-givenchy'),
  ('Cristóbal Balenciaga', 'cristobal-balenciaga'),
  ('Gianni Versace', 'gianni-versace'),
  ('Donatella Versace', 'donatella-versace'),
  ('Giorgio Armani', 'giorgio-armani'),
  ('Miuccia Prada', 'miuccia-prada'),
  ('Valentino Garavani', 'valentino-garavani'),
  ('Alessandro Michele', 'alessandro-michele'),
  ('Tom Ford', 'tom-ford'),
  ('Raf Simons', 'raf-simons'),
  ('Phoebe Philo', 'phoebe-philo'),
  ('Nicolas Ghesquière', 'nicolas-ghesquiere'),
  ('Rei Kawakubo', 'rei-kawakubo'),
  ('Yohji Yamamoto', 'yohji-yamamoto'),
  ('Issey Miyake', 'issey-miyake'),
  ('Kenzo Takada', 'kenzo-takada'),
  ('Pierre Cardin', 'pierre-cardin'),
  ('Jean-Paul Gaultier', 'jean-paul-gaultier'),
  ('Thierry Mugler', 'thierry-mugler'),
  ('Olivier Rousteing', 'olivier-rousteing'),
  ('Stella McCartney', 'stella-mccartney'),
  ('Vivienne Westwood', 'vivienne-westwood'),
  ('John Galliano', 'john-galliano'),
  ('Marc Jacobs', 'marc-jacobs'),
  ('Alexander McQueen', 'alexander-mcqueen'),
  ('Sarah Burton', 'sarah-burton'),
  ('Clare Waight Keller', 'clare-waight-keller'),
  ('Riccardo Tisci', 'riccardo-tisci'),
  ('Hedi Slimane', 'hedi-slimane'),
  ('Kim Jones', 'kim-jones'),
  ('Demna Gvasalia', 'demna-gvasalia'),
  ('Virgil Abloh', 'virgil-abloh'),
  ('Pierpaolo Piccioli', 'pierpaolo-piccioli'),
  ('Maria Grazia Chiuri', 'maria-grazia-chiuri'),
  ('Jil Sander', 'jil-sander'),
  ('Donna Karan', 'donna-karan'),
  ('Michael Kors', 'michael-kors'),
  ('Diane von Fürstenberg', 'diane-von-furstenberg'),
  ('Tory Burch', 'tory-burch'),
  ('Carolina Herrera', 'carolina-herrera'),
  ('Oscar de la Renta', 'oscar-de-la-renta'),
  ('Tommy Hilfiger', 'tommy-hilfiger'),
  ('Vera Wang', 'vera-wang'),
  ('Thom Browne', 'thom-browne'),
  ('Jeremy Scott', 'jeremy-scott'),
  ('Jason Wu', 'jason-wu'),
  ('Prabal Gurung', 'prabal-gurung'),
  ('Naeem Khan', 'naeem-khan'),
  ('Zac Posen', 'zac-posen'),
  ('Rick Owens', 'rick-owens'),
  ('Dries Van Noten', 'dries-van-noten'),
  ('Ann Demeulemeester', 'ann-demeulemeester'),
  ('Martin Margiela', 'martin-margiela'),
  ('Alber Elbaz', 'alber-elbaz'),
  ('Pierre Balmain', 'pierre-balmain'),
  ('Tony Ward', 'tony-ward'),
  ('Elie Saab', 'elie-saab'),
  ('Zuhair Murad', 'zuhair-murad'),
  ('Georges Hobeika', 'georges-hobeika'),
  ('Mohammed Ashi', 'mohammed-ashi'),
  ('Jean Patou', 'jean-patou'),
  ('Jeanne Lanvin', 'jeanne-lanvin'),
  ('Nina Ricci', 'nina-ricci'),
  ('Elsa Schiaparelli', 'elsa-schiaparelli'),
  ('Sybilla', 'sybilla'),
  ('Paco Rabanne', 'paco-rabanne'),
  ('Manolo Blahnik', 'manolo-blahnik'),
  ('Jonathan Anderson', 'jonathan-anderson'),
  ('Paul Smith', 'paul-smith'),
  ('Daniel Lee', 'daniel-lee'),
  ('Victoria Beckham', 'victoria-beckham'),
  ('Simone Rocha', 'simone-rocha'),
  ('Molly Goddard', 'molly-goddard'),
  ('Grace Wales Bonner', 'grace-wales-bonner'),
  ('Christopher Kane', 'christopher-kane'),
  ('Katharine Hamnett', 'katharine-hamnett'),
  ('Sabyasachi Mukherjee', 'sabyasachi-mukherjee'),
  ('Manish Malhotra', 'manish-malhotra'),
  ('Anita Dongre', 'anita-dongre'),
  ('Rahul Mishra', 'rahul-mishra'),
  ('Ritu Kumar', 'ritu-kumar'),
  ('Gaurav Gupta', 'gaurav-gupta'),
  ('Tarun Tahiliani', 'tarun-tahiliani'),
  ('Masaba Gupta', 'masaba-gupta'),
  ('Junya Watanabe', 'junya-watanabe'),
  ('Chitose Abe', 'chitose-abe'),
  ('Nigo', 'nigo'),
  ('Takahiro Miyashita', 'takahiro-miyashita'),
  ('Hiroshi Fujiwara', 'hiroshi-fujiwara'),
  ('Yoon Ahn', 'yoon-ahn'),
  ('Anna Sui', 'anna-sui'),
  ('Ralph Lauren', 'ralph-lauren'),
  ('Perry Ellis', 'perry-ellis'),
  ('Billy Reid', 'billy-reid'),
  ('Heron Preston', 'heron-preston'),
  ('Matthew Williams', 'matthew-williams'),
  ('Telfar Clemens', 'telfar-clemens'),
  ('Kerby Jean-Raymond', 'kerby-jean-raymond'),
  ('Eckhaus Latta', 'eckhaus-latta'),
  ('Hillary Taymour', 'hillary-taymour'),
  ('Aurora James', 'aurora-james'),
  ('LaQuan Smith', 'laquan-smith'),
  ('Peter Do', 'peter-do'),
  ('Marine Serre', 'marine-serre'),
  ('Simon Porte Jacquemus', 'simon-porte-jacquemus'),
  ('Olivier Theyskens', 'olivier-theyskens'),
  ('Pascal Millet', 'pascal-millet'),
  ('Casey Cadwallader', 'casey-cadwallader'),
  ('Kris Van Assche', 'kris-van-assche'),
  ('Haider Ackermann', 'haider-ackermann'),
  ('Hussein Chalayan', 'hussein-chalayan'),
  ('Roland Mouret', 'roland-mouret'),
  ('Alice Temperley', 'alice-temperley'),
  ('Emilio Pucci', 'emilio-pucci'),
  ('Kean Etro', 'kean-etro'),
  ('Angela Missoni', 'angela-missoni'),
  ('Salvatore Ferragamo', 'salvatore-ferragamo'),
  ('Brunello Cucinelli', 'brunello-cucinelli'),
  ('Ermanno Scervino', 'ermanno-scervino'),
  ('Alberta Ferretti', 'alberta-ferretti'),
  ('Francesco Risso', 'francesco-risso'),
  ('Dean & Dan Caten', 'dean-dan-caten'),
  ('Roberto Cavalli', 'roberto-cavalli'),
  ('Peter Dundas', 'peter-dundas'),
  ('Fausto Puglisi', 'fausto-puglisi'),
  ('Ian Griffiths', 'ian-griffiths'),
  ('Silvia Venturini Fendi', 'silvia-venturini-fendi'),
  ('Matthieu Blazy', 'matthieu-blazy'),
  ('Sabato De Sarno', 'sabato-de-sarno'),
  ('Lucia Silvestri', 'lucia-silvestri'),
  ('Dolce & Gabbana', 'dolce-gabbana'),
  ('Jonny Johansson', 'jonny-johansson'),
  ('Filippa K', 'filippa-k'),
  ('Tiger of Sweden', 'tiger-of-sweden'),
  ('Ditte Reffstrup', 'ditte-reffstrup'),
  ('Helmut Lang', 'helmut-lang'),
  ('Rag & Bone', 'rag-bone'),
  ('Proenza Schouler', 'proenza-schouler'),
  ('Gabriela Hearst', 'gabriela-hearst'),
  ('Brandon Maxwell', 'brandon-maxwell'),
  ('Jonathan Simkhai', 'jonathan-simkhai'),
  ('Christopher John Rogers', 'christopher-john-rogers'),
  ('Thebe Magugu', 'thebe-magugu'),
  ('Sindiso Khumalo', 'sindiso-khumalo'),
  ('Rich Mnisi', 'rich-mnisi'),
  ('Laduma Ngxokolo', 'laduma-ngxokolo'),
  ('Ozwald Boateng', 'ozwald-boateng'),
  ('Duro Olowu', 'duro-olowu'),
  ('Lisa Folawiyo', 'lisa-folawiyo'),
  ('Azzedine Alaïa', 'azzedine-alaia'),
  ('Julien Dossena', 'julien-dossena'),
  ('Christophe Lemaire', 'christophe-lemaire'),
  ('Isabel Marant', 'isabel-marant'),
  ('Véronique Leroy', 'veronique-leroy'),
  ('Nicolas Di Felice', 'nicolas-di-felice'),
  ('Nadège Vanhee-Cybulski', 'nadege-vanhee-cybulski'),
  ('Demna', 'demna'),
  ('Viktor & Rolf', 'viktor-rolf'),
  ('Iris van Herpen', 'iris-van-herpen'),
  ('Walter Van Beirendonck', 'walter-van-beirendonck'),
  ('Craig Green', 'craig-green'),
  ('Samuel Ross', 'samuel-ross'),
  ('Bianca Saunders', 'bianca-saunders'),
  ('Glenn Martens', 'glenn-martens'),
  ('Ibrahim Kamara', 'ibrahim-kamara'),
  ('Jerry Lorenzo', 'jerry-lorenzo'),
  ('Mike Amiri', 'mike-amiri'),
  ('Rhuigi Villaseñor', 'rhuigi-villasenor'),
  ('Ronnie Fieg', 'ronnie-fieg'),
  ('James Jebbia', 'james-jebbia'),
  ('Shawn Stussy', 'shawn-stussy'),
  ('Francesco Ragazzi', 'francesco-ragazzi'),
  ('Marcelo Burlon', 'marcelo-burlon'),
  ('Jun Takahashi', 'jun-takahashi'),
  ('Noir Kei Ninomiya', 'noir-kei-ninomiya'),
  ('Yasuko Furuta', 'yasuko-furuta'),
  ('Hiroki Nakamura', 'hiroki-nakamura'),
  ('Shinsuke Takizawa', 'shinsuke-takizawa'),
  ('Hiromichi Ochiai', 'hiromichi-ochiai'),
  ('Mihara Yasuhiro', 'mihara-yasuhiro'),
  ('Etudes Studio', 'etudes-studio'),
  ('Christelle Kocher', 'christelle-kocher'),
  ('Krizia', 'krizia'),
  ('Aspesi', 'aspesi'),
  ('Loro Piana', 'loro-piana'),
  ('Walter Chiapponi', 'walter-chiapponi'),
  ('Massimo Giorgetti', 'massimo-giorgetti'),
  ('Lorenzo Serafini', 'lorenzo-serafini'),
  ('Antonio Marras', 'antonio-marras'),
  ('Gabriele Colangelo', 'gabriele-colangelo'),
  ('Aquilano Rimondi', 'aquilano-rimondi'),
  ('Elisabetta Franchi', 'elisabetta-franchi'),
  ('Chiara Boni', 'chiara-boni'),
  ('Peter Pilotto', 'peter-pilotto'),
  ('Mary Katrantzou', 'mary-katrantzou'),
  ('Alex Perry', 'alex-perry'),
  ('Dion Lee', 'dion-lee'),
  ('Nicky & Simone Zimmermann', 'nicky-simone-zimmermann'),
  ('Camilla Franks', 'camilla-franks'),
  ('Kym Ellery', 'kym-ellery'),
  ('Roksanda Ilincic', 'roksanda-ilincic'),
  ('Richard Quinn', 'richard-quinn'),
  ('Giles Deacon', 'giles-deacon'),
  ('Paul Costelloe', 'paul-costelloe'),
  ('Eudon Choi', 'eudon-choi'),
  ('Sinead O''Dwyer', 'sinead-odwyer'),
  ('Rixo', 'rixo'),
  ('Alexandre Mattiussi', 'alexandre-mattiussi'),
  ('Judith Milgrom', 'judith-milgrom'),
  ('Evelyne Chetrite', 'evelyne-chetrite'),
  ('The Kooples', 'the-kooples'),
  ('Carven', 'carven'),
  ('Chemena Kamali', 'chemena-kamali'),
  ('Fusalp', 'fusalp'),
  ('Zadig & Voltaire', 'zadig-voltaire'),
  ('Arnaud Vaillant & Sébastien Meyer', 'arnaud-vaillant-sebastien-meyer'),
  ('Faith Connexion', 'faith-connexion'),
  ('Jean-Charles de Castelbajac', 'jean-charles-de-castelbajac'),
  ('Vionnet', 'vionnet'),
  ('Guillaume Henry', 'guillaume-henry'),
  ('Cacharel', 'cacharel'),
  ('Escada', 'escada'),
  ('Hugo Boss', 'hugo-boss'),
  ('Karl Lagerfeld Brand', 'karl-lagerfeld-brand'),
  ('Marina Hoermanseder', 'marina-hoermanseder'),
  ('Lena Hoschek', 'lena-hoschek'),
  ('Sander Lak', 'sander-lak'),
  ('Noon by Noor', 'noon-by-noor'),
  ('Saloni', 'saloni'),
  ('Toga', 'toga'),
  ('Kolor', 'kolor'),
  ('Lutz Huelle', 'lutz-huelle'),
  ('Nicholas Kirkwood', 'nicholas-kirkwood'),
  ('Sophia Webster', 'sophia-webster'),
  ('Rupert Sanderson', 'rupert-sanderson'),
  ('Jimmy Choo', 'jimmy-choo'),
  ('Giuseppe Zanotti', 'giuseppe-zanotti'),
  ('René Caovilla', 'rene-caovilla'),
  ('Santoni', 'santoni'),
  ('Tod''s', 'tods'),
  ('Borsalino', 'borsalino'),
  ('Philipp Plein', 'philipp-plein'),
  ('Amina Muaddi', 'amina-muaddi'),
  ('Christopher Esber', 'christopher-esber'),
  ('Rejina Pyo', 'rejina-pyo'),
  ('Georgia Hardinge', 'georgia-hardinge'),
  ('Marques Almeida', 'marques-almeida'),
  ('Acne Studios', 'acne-studios'),
  ('Our Legacy', 'our-legacy'),
  ('COS', 'cos'),
  ('H&M Studio', 'hm-studio'),
  ('Uniqlo U', 'uniqlo-u'),
  ('Sacai', 'sacai'),
  ('Visvim', 'visvim'),
  ('A Bathing Ape', 'a-bathing-ape'),
  ('Human Made', 'human-made'),
  ('Kiko Kostadinov', 'kiko-kostadinov'),
  ('Martine Rose', 'martine-rose'),
  ('Stefan Cooke', 'stefan-cooke'),
  ('Ambush', 'ambush'),
  ('Undercover', 'undercover'),
  ('Cav Empt', 'cav-empt'),
  ('Ader Error', 'ader-error'),
  ('Gentle Monster', 'gentle-monster'),
  ('Azzaro', 'azzaro'),
  ('Sies Marjan', 'sies-marjan'),
  ('Trussardi', 'trussardi'),
  ('Piquadro', 'piquadro'),
  ('Roberto Capucci', 'roberto-capucci'),
  ('Antonio Grimaldi', 'antonio-grimaldi'),
  ('Rabih Kayrouz', 'rabih-kayrouz'),
  ('Rami Al Ali', 'rami-al-ali'),
  ('Yousuf Akbar', 'yousuf-akbar'),
  ('Guo Pei', 'guo-pei'),
  ('Uma Wang', 'uma-wang'),
  ('Angel Chen', 'angel-chen'),
  ('Shiatzy Chen', 'shiatzy-chen'),
  ('Masha Ma', 'masha-ma'),
  ('Sean Suen', 'sean-suen'),
  ('Xander Zhou', 'xander-zhou'),
  ('Samuel Gui Yang', 'samuel-gui-yang'),
  ('Feng Chen Wang', 'feng-chen-wang'),
  ('Sankuanz', 'sankuanz'),
  ('Bruno Sialelli', 'bruno-sialelli'),
  ('Michèle Lamy', 'michele-lamy'),
  ('Guram Gvasalia', 'guram-gvasalia'),
  ('Eric Schlösberg', 'eric-schlosberg'),
  ('Baja East', 'baja-east'),
  ('Vaquera', 'vaquera'),
  ('Catherine Holstein', 'catherine-holstein'),
  ('Lela Rose', 'lela-rose'),
  ('Rebecca Minkoff', 'rebecca-minkoff'),
  ('Kate Spade', 'kate-spade'),
  ('Altuzarra', 'altuzarra'),
  ('Stuart Vevers', 'stuart-vevers'),
  ('Ralph Rucci', 'ralph-rucci'),
  ('Norman Norell', 'norman-norell'),
  ('Bill Blass', 'bill-blass'),
  ('Geoffrey Beene', 'geoffrey-beene'),
  ('Halston', 'halston'),
  ('Eugene Rabkin', 'eugene-rabkin'),
  ('Sophie Theallet', 'sophie-theallet'),
  ('Joseph Altuzarra', 'joseph-altuzarra'),
  ('Rosie Assoulin', 'rosie-assoulin'),
  ('Juan Carlos Obando', 'juan-carlos-obando'),
  ('Maryam Nassir Zadeh', 'maryam-nassir-zadeh'),
  ('Sandy Liang', 'sandy-liang'),
  ('Beckett Fogg & Piotrek Panszczyk', 'beckett-fogg-piotrek-panszczyk'),
  ('Shayne Oliver', 'shayne-oliver'),
  ('Edun', 'edun'),
  ('Rihanna', 'rihanna'),
  ('Kanye West', 'kanye-west'),
  ('Carlo Rivetti', 'carlo-rivetti'),
  ('CP Company', 'cp-company'),
  ('Woolrich', 'woolrich'),
  ('Arc''teryx Veilance', 'arcteryx-veilance'),
  ('And Wander', 'and-wander'),
  ('Snow Peak', 'snow-peak'),
  ('Outlier', 'outlier'),
  ('Errolson Hugh', 'errolson-hugh'),
  ('Stone Island', 'stone-island'),
  ('Jean Touitou', 'jean-touitou'),
  ('Charaf Tajer', 'charaf-tajer'),
  ('Aisha Ayensu', 'aisha-ayensu'),
  ('Amaka Osakwe', 'amaka-osakwe'),
  ('Kenneth Ize', 'kenneth-ize'),
  ('Deola Sagoe', 'deola-sagoe'),
  ('Ituen Basi', 'ituen-basi'),
  ('Sophie Zinga', 'sophie-zinga'),
  ('Loza Maleombho', 'loza-maleombho'),
  ('Anifa Mvuemba', 'anifa-mvuemba'),
  ('Gareth Pugh', 'gareth-pugh'),
  ('Manish Arora', 'manish-arora'),
  ('Bibhu Mohapatra', 'bibhu-mohapatra'),
  ('Rohit Bal', 'rohit-bal'),
  ('Anamika Khanna', 'anamika-khanna'),
  ('Abu Jani Sandeep Khosla', 'abu-jani-sandeep-khosla'),
  ('Payal Singhal', 'payal-singhal'),
  ('JJ Valaya', 'jj-valaya'),
  ('Shantanu & Nikhil', 'shantanu-nikhil'),
  ('Suneet Varma', 'suneet-varma'),
  ('Falguni Shane Peacock', 'falguni-shane-peacock'),
  ('Farah Khan Ali', 'farah-khan-ali'),
  ('Amit Aggarwal', 'amit-aggarwal'),
  ('Atsuko Kudo', 'atsuko-kudo'),
  ('Albert Kriemler', 'albert-kriemler'),
  ('Etam', 'etam'),
  ('La Perla', 'la-perla'),
  ('Wolford', 'wolford'),
  ('Agent Provocateur', 'agent-provocateur'),
  ('Intimissimi', 'intimissimi'),
  ('Yamamoto Kansai', 'yamamoto-kansai'),
  ('Maison Kitsuné', 'maison-kitsune'),
  ('Takahiromiyashita The Soloist', 'takahiromiyashita-the-soloist'),
  ('Tornado Mart', 'tornado-mart'),
  ('Hysteric Glamour', 'hysteric-glamour'),
  ('Beams', 'beams'),
  ('United Arrows', 'united-arrows'),
  ('Snidel', 'snidel'),
  ('Sonia Rykiel', 'sonia-rykiel'),
  ('Guy Laroche', 'guy-laroche'),
  ('Daniel Roseberry', 'daniel-roseberry'),
  ('Ungaro', 'ungaro'),
  ('Pelagia Kolotouros', 'pelagia-kolotouros'),
  ('A.P.C.', 'apc'),
  ('Maison Margiela', 'maison-margiela'),
  ('Juun.J', 'juunj'),
  ('Gosha Rubchinskiy', 'gosha-rubchinskiy'),
  ('Christion Wijnants', 'christion-wijnants'),
  ('Pierre-Louis Mascia', 'pierre-louis-mascia'),
  ('Laurence Dacade', 'laurence-dacade'),
  ('Alexandre Vauthier', 'alexandre-vauthier'),
  ('Georges Chakra', 'georges-chakra'),
  ('Stéphane Rolland', 'stephane-rolland'),
  ('Basil Soda', 'basil-soda'),
  ('Reem Acra', 'reem-acra'),
  ('Michael Cinco', 'michael-cinco'),
  ('Tamara Ralph', 'tamara-ralph'),
  ('Dundas', 'dundas'),
  ('Ludovic de Saint Sernin', 'ludovic-de-saint-sernin'),
  ('Mowalola Ogunlesi', 'mowalola-ogunlesi'),
  ('Supriya Lele', 'supriya-lele'),
  ('Ottolinger', 'ottolinger'),
  ('Kwaidan Editions', 'kwaidan-editions'),
  ('Serhat Isik & Benjamin Huseby', 'serhat-isik-benjamin-huseby'),
  ('Bally Brand', 'bally-brand'),
  ('Wooyoungmi', 'wooyoungmi'),
  ('Fendi Brand', 'fendi-brand'),
  ('Gucci Brand', 'gucci-brand'),
  ('Versace Brand', 'versace-brand'),
  ('Valentino Brand', 'valentino-brand'),
  ('Burberry Brand', 'burberry-brand'),
  ('Alexander Wang Brand', 'alexander-wang-brand'),
  ('Moncler Genius', 'moncler-genius'),
  ('Canada Goose', 'canada-goose'),
  ('The North Face', 'the-north-face'),
  ('Patagonia', 'patagonia')
ON CONFLICT (slug) DO NOTHING;